whiteboard:
  #annotation statuses specific to the each type of annotation
  annotations:
    message_frequency: 50
    status:
      start: 'DRAW_START'
      update: 'DRAW_UPDATE'
      end: 'DRAW_END'
  toolbar:
    colors:
      - value: '#000000' #black
        label: 'black'
      - value: '#ffffff' #white
        label: 'white'
      - value: '#ff0000' #red
        label: 'red'
      - value: '#ff8800' #orange
        label: 'orange'
      - value: '#ccff00' #electric lime
        label: 'eletricLime'
      - value: '#00ff00' #lime
        label: 'lime'
      - value: '#00ffff' #aqua/cyan
        label: 'cyan'
      - value: '#0088ff' #dodger blue
        label: 'dodgerBlue'
      - value: '#0000ff' #blue
        label: 'blue'
      - value: '#8800ff' #violet/indigo
        label: 'violet'
      - value: '#ff00ff' #magenta/fuchsia
        label: 'magenta'
      - value: '#c0c0c0' #silver
        label: 'silver'
    thickness:
      - value: 14
      - value: 12
      - value: 10
      - value: 8
      - value: 6
      - value: 4
      - value: 2
    font_sizes:
      - value: 36
      - value: 32
      - value: 28
      - value: 24
      - value: 20
      - value: 16
    tools:
      #text
      - icon: 'text_tool'
        value: 'text'
      #line
      - icon: 'linte_tool'
        value: 'line'
      #ellipse
      - icon: 'circle_tool'
        value: 'ellipse'
      #triangle
      - icon: 'triangle_tool'
        value: 'triangle'
      #rectangle
      - icon: 'rectangle_tool'
        value: 'rectangle'
      #pencil
      - icon: 'pen_tool'
        value: 'pencil'
      #pan and zoom hand
      - icon: 'hand'
        value: 'hand'
